### ISSUE TITLE
Activating FakeFS in view tests leads to Missing Template errors in RSpec.

### ISSUE THREAD

**Issue by sujoyg** [fakefs/fakefs#136]
When I activate FakeFS in a before block in a view test, the test starts failing with an such as the following:

ActionView::MissingTemplate: Missing template <my template> with {:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :png, :jpeg, :gif, :bmp, :tiff, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip, :xls], :handlers=>[:erb, :builder, :haml]}. Searched in:
- "/Users/xxx/code/xxx/app/views"

The error disappears if I do not activate FakeFS.

**Comment by chaitanyav** [comment]
This is still a issue with the gem.
