### ISSUE TITLE
assertion failure with minitest causes weird failure

### ISSUE THREAD

**Issue by jperry** [fakefs/fakefs#143]
Hi,

I'm using minitest/spec for testing and when the assertion fails it spits out a no directory failure for some reason:

```
  4) Error:
test_0001_should build a run list with the base role included(Cookbooks::RunListBuilder::#build_run_lists):
Errno::ENOENT: No such file or directory - No such file or directory - Usersjperryworkspacechefchef-repo
    /Users/jperry/.rvm/gems/ruby-1.9.2-p180@chef_repo/gems/fakefs-0.4.0/lib/fakefs/dir.rb:6:in `_check_for_valid_file'
    /Users/jperry/.rvm/gems/ruby-1.9.2-p180@chef_repo/gems/fakefs-0.4.0/lib/fakefs/dir.rb:104:in `mkdir'
    /Users/jperry/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/tempfile.rb:330:in `mkdir'
    /Users/jperry/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/tempfile.rb:145:in `block in initialize'
    /Users/jperry/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/tmpdir.rb:133:in `create'
    /Users/jperry/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/tempfile.rb:134:in `initialize'
    /Users/jperry/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/tempfile.rb:316:in `new'
    /Users/jperry/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/tempfile.rb:316:in `open'
```

When this happens it makes it hard to know why the assert didn't match.  The top of my test looks like this:

```

    include FakeFS

    before(:each) do
      FakeFS.activate!
      FileSystem.clear
    end

    after(:each) do
      FakeFS.deactivate!
    end

```

**Comment by misaka** [comment]
Hi @eventualbuddha,

I'm finding this is an issue when running FakeFS tests inside the project and it's masking errors raised inside the FakeFS tests, making development tougher. I think this issue should be re-opened with a focus on fixing it within FakeFS tests, at least.

I think there are 3 options:

1. Monkey patch Minitest as [done in pantry/pantry](https://github.com/pantry/pantry/commit/25ac659e8cc8bb8ba4a1f106e6db04a7d6f63558).
2. Create `/tmp` in `FakeFSTest`'s `setup` method as it's not unreasonable to expect `/tmp` to exist on UNIXy filesystems.
3. Create `/tmp` in `FakeFS::Filesystem#clear` (similar rationale as the above).

*2* seems sensible enough, although it'll mean changing a bunch of existing tests and I can probably create a PR for it.
