### ISSUE TITLE
brackets in filenames raise RegexpError

### ISSUE THREAD

**Issue by uishoo** [fakefs/fakefs#267]
Trying to create (FileUtils.touch) files which contain brackets [] raises this exception:
RegexpError: empty range in char class: /\Aproblem[atic----fil\Z/
in
fakefs-0.6.0/lib/fakefs/file_system.rb:152:in `find_recurser'

The problem seems fixed by adding a .gsub('[', '[') and .gsub(']', ']') after line 148 (right after the gsub where parenthesis ( ) are escaped with ( ) )
The change should be reviewed as I've no idea if that causes problems with the rest of the library

**Comment by gnikonorov** [comment]
Noting I'll take a look at this after issues with Rubocop in pull request https://github.com/fakefs/fakefs/pull/411 are resolved.

**Comment by gnikonorov** [comment]
This is still an issue, I will submit a pull request for it either today or tomorrow.

**Comment by gnikonorov** [comment]
Resolved by https://github.com/fakefs/fakefs/pull/412.
