### ISSUE TITLE
Dir#each should return an enumerator when no block is given

### ISSUE THREAD

**Issue by juandelgado** [fakefs/fakefs#284]
[Docs](http://ruby-doc.org/core-2.2.0/Dir.html#method-i-each) state that if no block is given ```each``` should return an enumerator. This fails on irb/pry:

```ruby
require 'fakefs/safe' 
FakeFS.activate! 
dir = Dir.new(Dir.getwd) 
dir.each
```
Errors out:

```bash
LocalJumpError: no block given (yield)
from /Users/xxx/.rvm/gems/ruby-2.1.3/gems/fakefs-0.6.0/lib/fakefs/dir.rb:29:in `each'
```

Am I missing something?

**Comment by sometimesfood** [comment]
This behaviour was probably not implemented originally because it was undocumented until Ruby 1.9.2.

I have prepared a simple patch but still have to add a proper test for it. I'll open a pull request once it's done.
