### ISSUE TITLE
gh-pages down.

### ISSUE THREAD

**Issue by ryanmjacobs** [fakefs/fakefs#285]
The gh-pages branch is there but [defunkt.io/fakefs](http://defunkt.io/fakefs) is down.

**Comment by tylercollier** [comment]
I am looking for documentation on `without`. I too would like to see [defunkt.io/fakefs](http://defunkt.io/fakefs) back up :-)

**Comment by ryanmjacobs** [comment]
@tylercollier I was able to browse it alright by cloning it and browsing it locally.

**Comment by tylercollier** [comment]
Good idea. How did you clone?

I tried the following, which was based on [these instructions](https://pages.github.com/):

```
$ git clone https://github.com/defunkt/defunkt.github.io
Cloning into 'defunkt.github.io'...
Username for 'https://github.com': tylercollier
Password for 'https://tylercollier@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/defunkt/defunkt.github.io/' not found
```

**Comment by ryanmjacobs** [comment]
The website is stored in the same repository, just in the `gh-pages` branch.
```
$ git clone https://github.com/defunkt/fakefs
$ git checkout gh-pages
```
Then, open `index.html` with your favorite browser. :grinning:

**Comment by tylercollier** [comment]
Ha, missed that! Thanks Ryan.

**Comment by matkoniecz** [comment]
Note that readme linkt o documentation at http://www.rubydoc.info/github/defunkt/fakefs

**Comment by grosser** [comment]
cleaned up readme
