### ISSUE TITLE
Possible incorrect implementation of Pathname#root?

### ISSUE THREAD

**Issue by badeball** [fakefs/fakefs#299]
Hi, thanks for an incredible library!

I suspect I might have found a bug regarding the implementation of `Pathname#root?`. Lets see at the actual implementation of the method.

```ruby
def root?
  !!(chop_basename(@path) == nil && /#{SEPARATOR_PAT}/o =~ @path)
end
```

You have implemented it as following.

```ruby
def root?
  !(chop_basename(@path).nil? && /#{SEPARATOR_PAT}/o =~ @path).nil?
end
```

However,  `!foo.nil?` is not equivalent of `!!foo`.

```ruby
require "pathname"
require "fakefs/safe"

puts Pathname.new("/foo/bar").root? # => false

FakeFS.with do
  puts Pathname.new("/foo/bar").root? # => true
end
```

**Comment by sometimesfood** [comment]
Yes, this is definitely a bug.

Apparently this was changed in a548517a in order to make fakefs pass the `DoubleNegation` rubocop check:

```diff
       def root?
-        !!(chop_basename(@path) == nil && /#{SEPARATOR_PAT}/o =~ @path)
+        !(chop_basename(@path).nil? && /#{SEPARATOR_PAT}/o =~ @path).nil?
       end
```
