### ISSUE TITLE
FakeFS Usage question

### ISSUE THREAD

**Issue by chazzly** [fakefs/fakefs#301]
I am trying to test a Chef Recipe which reads a list from a file and, if needed, adds to it.  The file does not exist on the server running the tests, so I started trying FakeFS.

When using FakeFS, another gem (chefspec) can't find it's files that it needs to do it's thing.  I have tried cloning the FS where the gem lives, I've tried cloning the specific file it's looking for, I've tried stubbing File with :open and :read .and_call_original.  I can't seem to find the right combination.

default.rb

```
currnt = []
File.open('/usr/path/to/file', 'r') do |f|
  while (l = f.gets)
    if l.include? 'members'
      currnt = l.strip.gsub(/\s+/, '').gsub('members', '').split(',')
    end
  end
end

puts currnt
```

default_spec.rb

```
require_relative './spec_helper.rb'
require 'chefspec'
require 'fakefs/spec_helpers'

describe 'default' do
  let(:chef_run) do
    ChefSpec::SoloRunner.converge(default.rb)
  end

  before(:all) do
    include FakeFS::SpecHelpers
    FakeFS.activate!
    FakeFS::FileSystem.clone('\/usr')
    FakeFS::FileSystem.clone('\/opt')     #### Where the gems live
    FileUtils.mkdir_p('/usr/path/to')
    f = FakeFS::FakeFile.new('\/usr\/path\/to\/file')
    f.content = "members server1,server2"
  end

  it 'should print member list' do
    expect(chef_run).to receive(:puts).with("server1,server2")
  end
end
```

Without FakeFS, I get:

```
Errno::ENOENT:
 No such file or directory @ rb_sysopen  - /usr/path/to/file
```

With FakeFS, I get:

```
Errno::ENOENT:
       No such file or directory  - /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/fauxhai-2.3.0/lib/fauxhai/platforms/chefspec/0.6.1.json
```

Any help suggestions would be appreciated.

**Comment by chazzly** [comment]
Meant to include this, I'm running:
ruby 2.1.4
fakefs 0.6.7
chefspec 4.2.0

I don't believe chefspec really has this has anything to do with it, since I traced down where the file is loaded and it's doing a simple file.exists? & file.read.

**Comment by sometimesfood** [comment]
Is there any specific reason why you escape the slashes in your paths?

```ruby
require 'fakefs/safe'

dir = '/usr/local/etc/logrotate.d'
dir_escaped = '\/usr\/local\/etc\/logrotate.d'

Dir["#{dir}/**/*"]
# => ["/usr/local/etc/logrotate.d/mysql", "/usr/local/etc/logrotate.d/mysql.default"]

FakeFS::FileSystem.clone(dir_escaped)
FakeFS { Dir["#{dir}/**/*"] }
# => []

FakeFS.clean
FakeFS::FileSystem.clone(dir)
FakeFS { Dir["#{dir}/**/*"] }
# => ["/usr/local/etc/logrotate.d/mysql", "/usr/local/etc/logrotate.d/mysql.default"]
```

However, I do not think that it is a good idea to clone directories as large as `/usr` or `/opt`. In my opinion the best way to get this working would be to make sure all components of your Chef setup are completely  loaded before using fakefs in a `FakeFS do` block or something similar.

**Comment by gnikonorov** [comment]
Hi @chazzly, can we close this issue?

**Comment by gnikonorov** [comment]
@chazzly - I am closing this issue since it's an answered usage question. Please feel free to re-open it.
