### ISSUE TITLE
Pathname#relative_path_from fails with valid paths

### ISSUE THREAD

**Issue by dotboris** [fakefs/fakefs#302]
When using FakeFS, `Pathname#relative_path_from` fails when given valid absolute paths. This is different from the behavior in MRI 2.2.1.

Here's an example demonstrating the problem:

``` ruby
require 'fakefs/safe'

p = Pathname.new('/foo/bar.txt')
p.relative_path_from Pathname.new('/foo')
#=> #<Pathname:bar.txt>

FakeFS.activate!
p = Pathname.new('/foo/bar.txt')
p.relative_path_from Pathname.new('/foo')
#=> blows up
```

This yields the following output:

```
$ ruby --version 
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
$ ruby test.rb 
/home/boris/.gem/ruby/2.2.0/gems/fakefs-0.6.0/lib/fakefs/pathname.rb:601:in `relative_path_from': different prefix: "/foo/bar.txt" and "/foo" (ArgumentError)
        from test.rb:9:in `<main>'
```

This is not expected behavior. The test script should not crash and the results with and without FakeFS should be the same.

**Comment by beraboris** [comment]
This bug may be platform specific.

I have a unit test that is affected by this issue. When I run the test from my machine with MRI 2.2.1 p85, I get the same error as in my test script. When the same unit test is run through Travis-CI (MRI 2.2.1 p85) I don't get the error.

For your information I am running Arch Linux 64bit.

I have updated my local ruby to 2.2.2p95 and my travis build to 2.2.2p95. I get the same issue. The test fails locally but works on travis.

**Comment by dotboris** [comment]
It's been about 4 years and I don't really need this anymore. Considering that this was platform specific, I'm just going to close this.
