### ISSUE TITLE
File.writable? always returns true, even when we don't have permission

### ISSUE THREAD

**Issue by davidshepherd7** [fakefs/fakefs#308]
`chmod` and `chown` are implemented but they don't affect the result of `File.writable?` (and various similar functions).

If it's intended to be not implemented it would be nice if it gave some kind of error, the current behaviour is very confusing.

**Comment by eventualbuddha** [comment]
I agree that's confusing. If anyone wants to write a PR for this I'd certainly take a look and merge.

**Comment by badeball** [comment]
I'd love to take the lead on something like this, as I currently have the spare time for it. However, I get kind of demotivated when looking at the current pull requests. Is this project maintained anymore?

**Comment by gnikonorov** [comment]
I'll take a look at this over the next few days and fix it if it's still an issue.

**Comment by gnikonorov** [comment]
I can reproduce this and will submit a fix for it.

**Comment by gnikonorov** [comment]
Resolved by https://github.com/fakefs/fakefs/pull/415.
