### ISSUE TITLE
Undefined method `copy_entry'

### ISSUE THREAD

**Issue by etolstoy** [fakefs/fakefs#323]
Hi! Thanks for a wonderful lib!

I'm getting the following error:

```
NoMethodError: undefined method `copy_entry' for FakeFS::FileUtils:Module
```

for this code:

```
FileUtils.copy_entry(template_path, install_path)
```

Is the lack of this method intentional?

**Comment by grosser** [comment]
nope, just oversight, please open a PR to add it

**Comment by olleolleolle** [comment]
Is this the implementation of this? 
https://github.com/fakefs/fakefs/pull/354

**Comment by grosser** [comment]
❤️
