### ISSUE TITLE
NoMethodError: undefined method `path' for FakeFS::File:Class

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [fakefs/fakefs#337]
There seems to be no method fir File.path.

When this code is invoked by my rspec test:

`file_list[File::path(file)] = File.mtime(file) unless ignore_list.include? file`

I get this error message:

`NoMethodError: undefined method `path' for FakeFS::File:Class`

**Comment by grosser** [comment]
Yep, please add it ... or use `file.to_s` instead

**Comment by andrewdavidmackenzie** [comment]
https://github.com/fakefs/fakefs/pull/338
