### ISSUE TITLE
FakeFS's file operations no longer accept Pathnames

### ISSUE THREAD

**Issue by CornedBee** [fakefs/fakefs#344]
Here's a trivial failing test case:

```
require 'fakefs/spec_helpers'
describe FakeFS::File do
  include FakeFS::SpecHelpers

  it 'accepts Pathname in ::open' do
    File.open(Pathname.new('/test'), 'wt') do |f|
      f.write('works')
    end
    expect(File.read('/test')).to eq('works')
  end
end
```

This is because `File::initialize` passes every path through `Filesystem::find`, which (since 0.7.0) uses `Globber::expand` to find multiple matches. However, that method starts with this line:

```
return [pattern] if pattern[0] != '{' || pattern[-1] != '}'
```

and `Pathname` does not have an index operator. Thus the tests fails:

```
Failures:

  1) FakeFS::File accepts Pathname in #open
     Failure/Error:
       File.open(Pathname.new('/test'), 'wt') do |f|
         f.write('works')
       end

     NoMethodError:
       undefined method `[]' for #<FakeFS::Pathname:/test>
     # ./spec/ffs_spec.rb:7:in `open'
     # ./spec/ffs_spec.rb:7:in `block (2 levels) in <top (required)>'
```

The solution would be to either call `to_s` on the incoming path in `Globber::expand`, or make it explicitly handle `Pathname` correctly (by returning a single match, since `Pathname`s aren't globs).

**Comment by CornedBee** [comment]
I just realized this is pull request  #336.

**Comment by tovodeverett** [comment]
Yup - just about to post such.  I submitted it back in February but there has been no movement.  That pull request also addresses some issues with Rails, but there has been no movement on getting it merged and I don't have the privileges to do so.

**Comment by grosser** [comment]
FYI don't assume a maintainer is watching all open PRs ... ping them :)

**Comment by grosser** [comment]
closing this since it's a duplication ... @CornedBee please check out the PR and see if it looks good
