### ISSUE TITLE
Website link is broken

### ISSUE THREAD

**Issue by michaelmior** [fakefs/fakefs#345]
http://defunkt.io/fakefs/ no longer exists

**Comment by grosser** [comment]
thx, updated!

**Comment by michaelmior** [comment]
@grosser I was actually referring to the link at the top of the GH page https://github.com/fakefs/fakefs

**Comment by grosser** [comment]
@smtlaissezfaire can you edit that ?

**Comment by Skarlso** [comment]
@grosser No, he shouldn't be able to. There should be an edit button right next to the text. Just click it and voila.. :)

**Comment by grosser** [comment]
I don't have it

**Comment by Skarlso** [comment]
Only the owner of the repository would have that link, I think. :/

**Comment by grosser** [comment]
done!
