### ISSUE TITLE
Using FakeFS to mock relative path

### ISSUE THREAD

**Issue by Skarlso** [fakefs/fakefs#348]
Hi. 

So, I've been scouring the web for some up-to-date tutorials on how to use FakeFS with not avail. It would be nice to have a comprehensive guide, but anyways. 

I'm trying to use it to mock out a relative path for a configuration file loader, I have which does this:

```ruby
require 'yaml'

# MineConfig is a configuration loader
class MineConfig
  attr_reader :loglevel, :profile, :upload_path
  def initialize
    config = YAML.load_file(File.join(__dir__, '../../cfg/config.yml'))
    @loglevel = config['loglevel']
    @profile = ENV.fetch('AWS_DEFAULT_PROFILE', 'default')
    # Upload path is used so files can sit anywhere.
    @upload_path = config['upload_path']
  end
end
```

Very simple. It just loads a config yml and then sets up some properties for this class. It sits in a GEM, so ../../cfg is where the file sits relative to this file. 

I have a test file for this like this:

```ruby
require 'mine_config'
require 'fakefs/spec_helpers'
require 'spec_helper'

describe MineConfig do
  describe '#initialize', fakefs: true do
    before :each do
      FakeFS do
        FileUtils.mkdir_p('/../cfg')
        File.open('/../../cfg/config.yml', 'w') do |f|
          f.puts('loglevel: INFO')
          f.puts('upload_path: /drop')
        end
      end
    end

    let(:mineconfig) { MineConfig.new }
    it 'should be an instance of MineConfig' do
      expect(mineconfig).instance_of? MineConfig
    end

    it 'correctly setup variables which are loaded from the config file' do
      puts mineconfig.loglevel
    end
  end
end
```

These sit in various modules which I left out, that doesn't concern matters. This is working from FileFS's side. if I say `p f` I can see that it creates a proper FilesFS object. But this fails in the class on trying to load the config file, saying that `No such file or directory.`.

I think I have everything setup. I have a spec_helper.rb which gets loaded, looking like this: 

```ruby
require 'fakefs/spec_helpers'

RSpec.configure do |config|
  config.include FakeFS::SpecHelpers, fakefs: true
end
```

And I'm running tests via rake: 

```ruby
require 'bundler'
Bundler::GemHelper.install_tasks

begin
  require 'rspec/core/rake_task'

  RSpec::Core::RakeTask.new(:spec)

  task default: :spec
rescue LoadError => le
  puts "There was a problem loading RSpec. #{le}."
end
```

So.... What the hell am I doing wrong here? Because obviously, I'm doing something wrong here. But I couldn't find anything on this kind of setup or tutorial out there. 

Any help is greatly appreciated! 

Thanks!

**EDIT**: Figured it out!!! I have to clone the filesystem I'm working in. F*ck yeah!

```ruby
    before :each do
      FakeFS do
        # include FakeFS::SpecHelpers
        # FakeFS.activate!
        FakeFS::FileSystem.clone(__dir__)
        FileUtils.mkdir_p(File.join(__dir__, '../cfg'))
        File.open(File.join(__dir__, '../cfg/config.yml'), 'w') do |f|
          f.puts('loglevel: WARN') # this will display warn although the original contains INFO
          f.puts('upload_path: /drop')
        end
      end
    end
```

Is this correct like this?

**Comment by Skarlso** [comment]
I've put that part into the spec helper with a shared_samples before each setup and now everything works without having to duplicate stuff. 

The utter lack of documentation is still an issue though. :-/

**Comment by grosser** [comment]
can you fix the docs ? :)

**Comment by Skarlso** [comment]
@grosser I would if there would be any....? :)

**Comment by grosser** [comment]
can you write down what you would have liked to see / what info you learned ?
... for now just dump it into the Readme I guess ...

**Comment by Skarlso** [comment]
Sure. I'll open a PR. :-)

**Comment by Skarlso** [comment]
@grosser Done https://github.com/fakefs/fakefs/pull/349.
