### ISSUE TITLE
Pathname.open should check #activated?

### ISSUE THREAD

**Issue by limitusus** [fakefs/fakefs#360]
I wrote tests changing `FakeFS.activated?` by calling `FakeFS.activate!` and `FakeFS.deactivate!`.
I noticed that sometimes my tests fail with `Errno::ENOENT: No such file or directory`, depending on rspec seed.

Then I could find the reproducible code:
```ruby
require 'fakefs/safe'
FakeFS.activate!
p = Pathname.new("/tmp/x")  # FakeFS::Pathname
FakeFS.deactivate!
p.open("w+")  # throws Errno::ENOENT
```
Of course `/tmp` exists in the real filesystem, not in FakeFS filesystem.

It may be true `FakeFS::Pathname` should only be used when `FakeFS.activated?` is true, but it happens when `/tmp/x` is a configuration parameter (in test) and is loaded before, in another test.

I found checking `FakeFS.activate?` mitigates this issue by patching `FakeFS::Pathname#open` in `spec_helper.rb` like below, but is it the correct way?
Or should I call like `open(p.to_s, ...)` at any time?

```ruby
module FakeFS
  class Pathname
    def open(mode='r', perm=0666)
      if FakeFS.activated?
        open(mode, perm)
      else
        ::File.open(self.to_s, mode, perm)
      end
    end
  end
end
```

I would be happy if there is a good way to bypass this problem.

**Comment by grosser** [comment]
If other things behave the same way then I'd rather keep this consistent
... for example does File.open(f) return a FakeFS::File that then reads
from fakefs no matter if it is active ?

**Comment by limitusus** [comment]
That's true...I think I need to reinitiate configuration structure for tests...
