### ISSUE TITLE
DOCS: don't blame pp for "superclass mismatch for class File" errors

### ISSUE THREAD

**Issue by ifreecarve** [fakefs/fakefs#364]
This is a request to adjust some documentation, particularly the README:

> FakeFs vs `pp` --- `TypeError: superclass mismatch for class File`
> `pp` and `fakefs` collide, `require 'pp'` then `require 'fakefs'`.

This implies the following things:

1. `fakefs` can collide with packages (which is true)
2. `pp` is an example of a package that can collide with `fakefs` (which is true, but perhaps a weaker statement than "`pp` is almost certainly the package that's colliding, even if you're not using it")
3. If you suspect a collision with another package, just requiring that package before `fakefs` should fix the issue (maybe false)
4. If you're getting this collision error without using `pp`, it could be a different package colliding (probably false)

Since I wasn't using `pp`, it seemed reasonable for me to look elsewhere for the source of the problem.  Whoops.  This led me down a deep rabbit hole of trying to find out which package or class of mine might have been causing the error.  In the end, surprisingly, I fixed the problem by adding a `pp` reference to my project (as suggested here):
https://github.com/fakefs/fakefs/issues/99#issuecomment-126941785

At the very least, the documentation should be amended to say "even if you don't actually use or reference `pp` anywhere, this problem can still be fixed by adding a `pp` reference".  At best, a brief description of how to test whether a given package and `fakefs` are colliding would be very helpful in debugging.

**Comment by grosser** [comment]
Please make the PR with the changes you want :)

**Comment by ifreecarve** [comment]
No problem.  Can you explain whether the gemfile-based fix will work for installed gems?  Is that the most reliable/canonical way?

**Comment by grosser** [comment]
Your explanation sounds right to me ... the issue is that FakeFS defines File and then other gems can collide with that ... also means that whatever other gems add to File might get lost, but so far that has not been an issue.
