### ISSUE TITLE
Next JRuby: to_output_stream, to_input_stream

### ISSUE THREAD

**Issue by olleolleolle** [fakefs/fakefs#377]
The next JRuby will have aliases for `to_output_stream`, `to_input_stream`.

https://github.com/jruby/jruby/commit/c22987adcf0d2dd32b37fd4078f60dcf68aea73b

When `master` is released as 9.2.0.0, this change will be in there.

There's code to unset to_outputstream, to_inputstream: that code will need a tiny update.

**Comment by grosser** [comment]
could you prepare a PR that does some version detection to prepare for that ?

**Comment by olleolleolle** [comment]
@grosser Could it be a `#respond_to?` check?

**Comment by grosser** [comment]
can be whatever you want/works :)
