### ISSUE TITLE
All fail invocations need to coerce pathnames to strings

### ISSUE THREAD

**Issue by malakai97** [fakefs/fakefs#391]
Behavior we expect to see: useful error messages, e.g. file doesn't exist

Behavior we see: 
```
    TypeError:
       no implicit conversion of FakeFS::Pathname into String
```

Where we see it:  Basically anywhere that there is an invocation of `fail` that passes an object that could be a Pathname, which is a lot of places.  These `fail` invocations are not collected in one location at all.

**Comment by malakai97** [comment]
I'm not able to reproduce these errors in the tests. Perhaps a loading issue?

**Comment by malakai97** [comment]
My recommendation is to wrap the various reasons you'd call `fail` into methods, apply those methods everywhere, and write a test for this bug against those methods. I can supply this change.

**Comment by grosser** [comment]
seems to also not work with regular pathname :(
```
>> Pathname.new 'xxx'
=> #<Pathname:xxx>
>> raise _
```

grep for all the `fail` and add `.to_s` where it makes sense ?

**Comment by malakai97** [comment]
While `fail` and `raise` will misbehave when given a Pathname, FileUtils and friends seem to coerce it at some point:

```ruby
irb(main):007:0> FileUtils.cp(Pathname.new("/does/not/exist"), "here")
Errno::ENOENT: No such file or directory @ rb_sysopen - /does/not/exist
```

While your suggestion of grepping would work, it's also not self-documenting. Contributors will forget or not notice, and the issue will crop up intermittently. That's why I want to box it up. In a normal library, we'd have our own exception classes which could do the type-casting for us, but as we're trying to look like the system libs that's not an option.

**Comment by grosser** [comment]
could overrode fail to stringify things when they are Pathnames ... not
super nice though ...
grep-replace might not be a catch-all solution, but so far there have been
very few complains about this kind of issue, so maybe it's good enough

**Comment by malakai97** [comment]
I might whip something up over the next six days or so

**Comment by malakai97** [comment]
I haven't forgotten about this, just been busy.

**Comment by basvk** [comment]
Got bitten by this today. 
Solved it by adding a `to_str` method (that calls `to_s`) to the FakeFS::Pathname class.

**Comment by grosser** [comment]
sadly pathname itself does not have to_str :(

```
NoMethodError (undefined method `to_str' for #<Pathname:a>)
Did you mean?  to_s
```

**Comment by basvk** [comment]
> sadly pathname itself does not have to_str :(
Indeed...
Which looks like an omission in the Ruby Pathname implementation, because even the documentation for the Core Methods of the Pathname class says "These methods are effectively manipulating a String, because that's all a path is."
So a `to_str` method would be appropriate for this class.

In the meantime, would it be a sin to have FakeFS monkeypatch `to_str` into Ruby's Pathname class? (only when FakeFS has been included and is active, and only when it doesn't exist yet)?

**Comment by basvk** [comment]
Forget about the above suggestion, it would make tests using FakeFS pass when using String + Pathname concatenations (with a '+' operator) that would otherwise fail IRL.

I guess there is no quick solution here, the only option is to add `.to_s` where Pathname is concatenated, or to use string interpolation everywhere.

LMK if you'd like me to create a PR for that.

**Comment by grosser** [comment]
yes, please make that PR, but don't delete string tests like in the commit above, but add new pathname tests.

**Comment by basvk** [comment]
> but don't delete string tests like in the commit above, but add new pathname tests.

The duplication is staggering, as everything needs to be tested with and without Pathname parameters... (I chose to avoid duplication where it made sense in my commit)

Would you rather:
1) have all (relevant) tests duplicated in a separate file specially for testing with Pathname entries (cleaner code, but easy to forget to add test cases in both test files)
2) or have Pathname tests mixed between string tests (separate test functions, same file) (lots of semi redundant tests)
3) or have Pathname tests included inside the current test functions (same test functions, same file) (messier code)?

**Comment by grosser** [comment]
either:
 - add a few pathname tests that document the current bugs
 - make all tests execute with and without pathname
[true, false].each do |pathname|
  def path(to)
    @with_pathname ? Pathname.new(to) : to
  end
  before { @with_pathname = pathname }
  it "foo" do
    File.read(path("foo/bar")).must_equal "blah"
  end

**Comment by basvk** [comment]
>- make all tests execute with and without pathname

I thought about using a similar construct `[true, false].each do |pathname| ...` like you suggested, but I can't imagine any way of getting that done with MiniTest (with RSpec it's simple indeed).
Any hints?

**Comment by grosser** [comment]
covert from `def test_foo` to `it "foo"`

**Comment by basvk** [comment]
> covert from `def test_foo` to `it "foo"`

Ah I see, I'm not familiar with Minitest, I didn't know it understood spec syntax.
Anyway converting almost all tests would take me more time than I'm willing to spend on this issue...

In the meantime (with the help of some smart grepping and scripting) I've implemented it in a different way (see commit above). At least it makes it very clear when Pathnames are tested...

I also found a few more issues that I missed in my first commit.

**Comment by grosser** [comment]
can you turn this into a PR ?

**Comment by grosser** [comment]
looks good, same approach, different flavor :)

**Comment by basvk** [comment]
See: https://github.com/fakefs/fakefs/pull/426

**Comment by basvk** [comment]
whoops, looks like I offended Rubocop... Let me check that.

**Comment by grosser** [comment]
0.19.0

**Comment by malakai97** [comment]
Good work! Sorry I ended up forgetting about this after all. I need to check my github notifications more than once a year.
