### ISSUE TITLE
FileUtils::remove_entry_secure(path, force=true) doesn't work

### ISSUE THREAD

**Issue by harvimt** [fakefs/fakefs#396]
remove_entry_secure is made as an alias of `rm_rf` which isn't quite right, since rm_rf takes in an options hash, but remove_entry_secure takes in keyword arguments.

workaround:

```ruby
module FakeFS
  module FileUtils
    def self.remove_entry_secure(path, force=false)
      FakeFS::FileUtils.rm_rf(path, {force: force})
    end
  end
end
```

**Comment by grosser** [comment]
can you turn this into a PR ?

**Comment by grosser** [comment]
did not saw any fix coming in, so please do it :)

**Comment by grosser** [comment]
0.14.3
