### ISSUE TITLE
Add Glitter Integration to repo

### ISSUE THREAD

**Issue by gnikonorov** [fakefs/fakefs#414]
I think it would be convenient to integrate `Glitter` into this repo. `Glitter` ( https://gitter.im/ ) is a chatroom geared towards GitHub repositories. Users can authenticate with GitHub and join in on the conversation, asking questions, making comments, and assisting others. It would remove questions from our `issues` section and promote more active participation and involvement by members. 

We could also add `Glitter` to the `README` as a badge the top, similar to how we have `Travis` setup, and it looks like `Glitter` will do it automatically via a pull request.

@grosser thoughts? I don't think I have permissions to do so as  as `fakefs/fakefs` will not show up in my list of repos when I try and a make a Glitter channel.

**Comment by grosser** [comment]
prefer not to since:
 - it makes issues not searchable / not linkable / removes history
 - it encourages questions without context / is more overhead for maintainers
 - no maintainer will be available in that channel / there is no active fakefs community, just 1-2 issues per month and their PRs

**Comment by gnikonorov** [comment]
That is true, I didn't really think of that at the time.
