### ISSUE TITLE
FakeFS is more forgiving when copying file to not existing directory

### ISSUE THREAD

**Issue by pawlik** [fakefs/fakefs#421]
Here's native ruby behavior (2.4.3)

Tested in "0.13.2" and "0.18.0"

```pry
[1] pry(main)> FileUtils.touch('/tmp/file123.txt')
=> ["/tmp/file123.txt"]
[2] pry(main)> FileUtils.cp('/tmp/file123.txt', '/tmp/unexisting/file123.txt')
Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/unexisting/file123.txt
from /home/toptal/.rvm/rubies/ruby-2.4.3/lib/ruby/2.4.0/fileutils.rb:1290:in `initialize'
```

It raises and error. Here's what happens when we activate FakeFS:

```pry
[3] pry(main)> require 'fakefs'
=> true
[4] pry(main)> FileUtils.mkdir('/tmp')
=> ["/tmp"]
[5] pry(main)> FileUtils.touch('/tmp/file123.txt')
=> ["/tmp/file123.txt"]
[6] pry(main)> FileUtils.cp('/tmp/file123.txt', '/tmp/unexisting/file123.txt')
=> nil
[7] pry(main)> File.new('/tmp/unexisting/file123.txt').exists?
=> true
```

Not only the exception is not raised, but the file is copied. This makes impossible to reproduce such cases in the specs.

**Comment by grosser** [comment]
sounds like a bug, can you open a PR to fix it ?

**Comment by gnikonorov** [comment]
@grosser @pawlik I can fix this issue over the next few days.

@pawlik please let me know if you’d rather do it. I’ll assume it’s up for grabs unless I hear otherwise

**Comment by pawlik** [comment]
I'll be more than happy to help, can you give me some pointers where to
start?

-- 
Typed with thumbs and sent with love from Boomerang
<http://boomerangandroid.com/?utm_source=b4a_signature&utm_medium=b4a_email_sig&utm_campaign=play_promote>

-----Original Message-----
Re: [fakefs/fakefs] FakeFS is more forgiving when copying file to not
existing directory (#421)

**Comment by pawlik** [comment]
@gnikonorov I'm stuck :( I've created the crude/basic spec to reproduce the issue: https://github.com/pawlik/fakefs/blob/bug-421/spec/fakefs/file_utils_spec.rb#L19 but I get

**Comment by pawlik** [comment]
Ok, I think something gets messed up with expectations when FakeFS is activated. This little monster at least reproduces the issue: 

```ruby
        exception = nil
        FakeFS do
          FileUtils.mkdir_p(dir)
          FileUtils.touch(source_file)

          begin
            FileUtils.cp(source_file, dest_file)
          rescue => exception
            puts "ERROR!"
          else
            puts "NO ERROR"
          end
        end

        expect(exception).to be_a(Errno::ENOENT)
```

I'll continue with the fix, and we can work on improving the specs later...

**Comment by pawlik** [comment]
I know it's an off-topic, but looking at the implementation (i.e. https://github.com/fakefs/fakefs/blob/e0660dd7f4b5c280b6cba2b87916c0c3cef41e37/lib/fakefs/fileutils.rb#L131) I don't think I'm comfortable using this project at all. I can't have `approx` implementation of the FS methods. Is this a fair summary, or am I missing something?

**Comment by gnikonorov** [comment]
@pawlik - I’m not sure offhand as I’ve started to contribute here fairly recently, perhaps @grosser might know ? 

I haven’t had issues with the cp command and there don’t seem to be any open issues.

**Comment by basvk** [comment]
Looks like the FakeFS implementation is not checking file permissions on most of its operations (this bug also happens with `File.read`, `File.write` and so on).

I will add some testcases. Looks like a couple of `File.readable?` and `File.writable?` need to be sprinkled throughout the code...

**Comment by grosser** [comment]
👍

**Comment by basvk** [comment]
So... not totally on topic, but how about file ownership? It isn't checked either and would be good to add it in as well.
That would bring a big amount of work in the tests though, because most test cases start with something like `FileUitls.mkdir_p '/path'`, which will fail except when you run tests as root...

**Comment by grosser** [comment]
yeah idk ... at some point it's demising returns ... how many people really need this feature that then all users would have to pay for in terms of performance :(

**Comment by basvk** [comment]
Well uhm at least one user would be happy with it 😅 (and I know how to scratch my itches)

I don't know how to test corner cases due to ownership issues without some way of faking the fs...
But yeah, most people probably don't need it or you'd have a ton of issues about it already.
Will see what I can do in my fork.

**Comment by grosser** [comment]
... just use a real filesystem ... Dir.mktmpdir is your friend :D
