### ISSUE TITLE
please add ruby2.7 support

### ISSUE THREAD

**Issue by boutil** [fakefs/fakefs#437]
As mentionned in https://github.com/fakefs/fakefs/pull/436, the tests do not pass anymore on ruby2.7.
Causes are:
- tremendous ammount of warning caused by deprecation of taint/tainted?/$SAFE etc. on ruby2.7
  https://bugs.ruby-lang.org/issues/16131
- additional double splatter operators appearing in constructor of `tempfile.rb` of ruby
https://github.com/ruby/ruby/blob/b76a21aa45fff75909a66f8b20fc5856705f7862/lib/tempfile.rb#L127
https://github.com/ruby/ruby/blob/b76a21aa45fff75909a66f8b20fc5856705f7862/lib/tempfile.rb#L129
, which does not work anymore with the `create` method of `lib/fakefs/dir.rb`

Could you please fix this to add ruby2.7 support? Thanks in advance.

**Comment by lucaskanashiro** [comment]
Any news here?

**Comment by grosser** [comment]
still waiting for PR

**Comment by grosser** [comment]
v1.1.0 thanks to @terceiro
