### ISSUE TITLE
tests for the verbose option in cp and mv fail randomly under ruby 2.7

### ISSUE THREAD

**Issue by terceiro** [fakefs/fakefs#439]
Hi,

while running the tests I noticed that sometimes one of the tests for the verbose option will fail. I just ran the tests ~100 times, and seen the following failures (with counts):

```
2 FakeFSTest#test_file_utils_cp_allows_verbose_option
1 FakeFSTest#test_file_utils_cp_r_allows_verbose_option
3 FakeFSTest#test_mv_accepts_verbose_option
```

The failure rate looks like something between 5 and 10%.

I'm seeing this on ruby 2.7 on Debian sid/unstable:

```
$ ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
I can also consistently reproduce an even higher failure rate (20%) using the `ruby:2.7` docker image, but **not** with the `ruby:2.6` one.

This is probably a timing issue somewhere; not sure yet where.

**Comment by grosser** [comment]
try running with the same `--seed` to nail the order down, and then only run a single case to make sure it's not polluted by maybe other threads running in the background
