### ISSUE TITLE
Regression: FakeFS::File became non-IO

### ISSUE THREAD

**Issue by limitusus** [fakefs/fakefs#447]
I have a code that depends on `#is_a?(IO)`, testing with FakeFS.
The test broke when FakeFS is upgraded to v1.2.1.

This very small code shows what changed in v1.2.0 to v1.2.1:

```ruby
require 'fakefs'

f = FakeFS::File.open("/foo", "a")
p f.class
p f.is_a?(IO)
```

v1.2.0 output

```
FakeFS::File
true
```

v.1.2.1 output

```
FakeFS::File
false
```

I believe `FakeFS::File` should pretend `IO`. Is it correct?

**Comment by grosser** [comment]
thx!
... changed that by accident and it did not have any tests :(

1.2.2

**Comment by limitusus** [comment]
Thank you for quick fix!
