### ISSUE TITLE
Dir.open() { |foo| ... } differs from standard Dir.open

### ISSUE THREAD

**Issue by levenkov** [fakefs/fakefs#449]
What Dir.open from FakeFS does with passed block:

![image](https://user-images.githubusercontent.com/35109446/89283979-b9be2800-d656-11ea-81e5-d8398abe1536.png)

And what standard Dir.open with block does:

![image](https://user-images.githubusercontent.com/35109446/89284257-2afddb00-d657-11ea-9c07-c65557b6bcb4.png)

**Comment by grosser** [comment]
sounds correct, can you open a PR to fix it ?

**Comment by levenkov** [comment]
> sounds correct, can you open a PR to fix it ?

Sure👌
