### ISSUE TITLE
Dir.glob fails if chdir to a directory that contains plus signs '+'

### ISSUE THREAD

**Issue by gyfelton** [fakefs/fakefs#451]
Original code that reproduces the error. Assuming the following file is created by FakeFS: `tmp/abc+cde/content.txt`
```
Dir.chdir('/tmp/abc+cde').do 
   Dir.glob('**/*') do |file|
      # Expected: content.txt
      # Actual: tmp/abc+cde/content.txt
   end
end
```
The reason for above is because in `self.glob` method of `dir.rb`, `%r{\A#{Dir.pwd}/?}` is evaluated as `\/tmp\/abc+cde` when it should be `\/tmp\/abc\+cde` (`%r` only escapes `/` not `+`)

The following test should be success when it is failing:
```
def test_dir_glob_special_char_in_dir_name
    FileUtils.mkdir_p '/abc+cde/python-3.4.1'
    FileUtils.mkdir_p '/abc+cde/python-2.7.8'
    Dir.chdir('/abc+cde') do
      assert_equal ['python-2.7.8', 'python-3.4.1'], Dir.glob('**/*')
    end
end
```

**Comment by grosser** [comment]
PR welcome, thx for the test!

**Comment by gyfelton** [comment]
@grosser Thanks, curious if using a fix on Globber will help here: https://github.com/fakefs/fakefs/issues/133

**Comment by grosser** [comment]
that's already released, so it does not work ? (you tried with latest ?)

**Comment by gyfelton** [comment]
resolved by above PR
