### ISSUE TITLE
`File.readlines(path, chomp: true)` isn't supported (standard)

### ISSUE THREAD

**Issue by cbortz** [fakefs/fakefs#453]
Given the following code:

```ruby
File.readlines(path, chomp: true)
```

When invoked in a fake filesystem, I receive this error:

```sh
ArgumentError: wrong number of arguments (given 2, expected 1)
```

As far as I can tell, Ruby's IO class has [supported the `:chomp` option since v2.5](https://ruby-doc.org/core-2.5.0/IO.html#method-c-readlines) (although [this blog post](https://blog.bigbinary.com/2017/03/07/io-readlines-now-accepts-chomp-flag-as-an-argument.html) suggests since v2.4). The general idea is that `#chomp` will be invoked on each item returned in the array.

Are y'all willing to support this? If so, I'm happy to open a PR for it within a day or so!

**Comment by grosser** [comment]
PR welcome as long as it does not get super-funky :)
