### ISSUE TITLE
Using requests with fakefs

### ISSUE THREAD

**Issue by davidorme** [fakefs/fakefs#469]
Hi,

Just in case anyone else comes across this edge case, we were using the `requests` package within a set of tests using `fakefs`. That gave us a consistent failure:

```
====================================================================================== short test summary info ======================================================================================
FAILED test/test_requests.py::test_requests_fake - OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /xxx/site-packages/cert...
==================================================================================== 1 failed, 1 passed in 2.33s ====================================================================================
```

The issue here is that `requests` relies on the `certifi` package for HTTPS certificate chains - and the underlying certificate bundle is only loaded when required, not when the `certifi` package is imported.

Once we figured out the problem, the solution is pretty simple: in the setup of the fake filesystem (probably as a fixture in `conftest.py`)

```
import certifi
fs.add_real_file(certifi.where())
```

**Comment by grosser** [comment]
this is the ruby library not python

**Comment by davidorme** [comment]
Ack, really sorry
