### ISSUE TITLE
File system and objects are not auto loaded on Ruby 3.0.4

### ISSUE THREAD

**Issue by alishersadikov** [fakefs/fakefs#483]
I am trying to upgrade the Ruby version from 2.7.6 to Ruby 3.0.4 in our Rails project and running into interesting issues. We are on     `fakefs` version 1.3.0 and trying to preserve that version through the upgrade. Therefore, the odds are that this issue is related to the configuration outside of `fakefs`, but still posting here to see if folks have any insight. The  issues I am seeing: 

1. Objects are not auto-loaded any more, throwing `Uninitialized constant XXX` errors. With the tests that use `FakeFS.with_fresh do.. end` block, if the test uses objects defined in different files of the project, I have to clone those files now. I am cloning these catch-all directories and it seems to resolve the issue for me. 
```
      FakeFS::FileSystem.clone(File.join(::Rails.root, "app"))
      FakeFS::FileSystem.clone(File.join(::Rails.root, "lib"))
      FakeFS::FileSystem.clone(File.join(::Rails.root, "spec"))
```
If I have to keep the cloning as above, does this introduce significant performance bottlenecks?

2. It seems like there is a distinction between these two ways of creating a directory and it was not like that before: 

```      
     FakeFS::FileUtils.mkdir(File.join(::Rails.root, "tmp"))
```

versus

```
      FakeFS::FileUtils.mkdir("tmp")
```

Thanks for this great gem and any input is appreciated!

**Comment by grosser** [comment]
A workaround would be to load everything before enabling fakefs (`Dir.glob` + `require` maybe)
If the behavior changed between ruby versions then I think that means that the old ruby used some internal api and the new version uses `File.read` or some other fakefs method.
It could help narrowing this down by making a simple example file (using bundler/inline) to reproduce this in 2 ruby versions ... I'd expect one of them to call some internal FakeFS method and the other to not do that.

**Comment by tovodeverett** [comment]
I'm surprised you haven't run into this issue before.  I've been having to clone since the dawn of time (Rails 4.x?).

I have no memory of how this code works - I wrote this 8+ years ago, but here it is in case it helps.  This is from `spec_helper.rb`:
``` ruby
# Support FakeFS helpers
require 'fakefs/spec_helpers'
require 'pp' # Resolves https://github.com/defunkt/fakefs/issues/215, https://github.com/defunkt/fakefs/issues/99

# Support for FakeFS::SpecHelpers::Rails
module FakeFS
  module SpecHelpers
    module Rails
      def self.extended(example_group)
        example_group.use_fakefs_rails(example_group)
      end

      def self.included(example_group)
        example_group.extend FakeFS::SpecHelpers
        example_group.extend self
      end

      def use_fakefs_rails(describe_block)
        describe_block.before :each do
          unless FakeFS::FileSystem.unarchive(:rails)
            FakeFS::FileSystem.clone(::Rails.root.join('app'))
            FakeFS::FileSystem.clone(::Rails.root.join('config'))
            FakeFS::FileSystem.clone(::Rails.root.join('public'))
            FakeFS::FileSystem.clone(Gem.loaded_specs['jquery-rails'].full_gem_path)
            FakeFS::FileSystem.clone(Gem.loaded_specs['coffee-script-source'].full_gem_path)
            FileUtils.mkdir_p('/tmp')
            FakeFS::FileSystem.archive(:rails)
          end
        end
      end
    end
  end
end
```

Then I just use `include FakeFS::SpecHelpers::Rails` in my rspec contexts.

The cool thing there is by using archive, I amortize the cost of cloning huge chunks of my Rails app across all the tests that need FakeFS.

**Comment by grosser** [comment]
nice trick!

**Comment by alishersadikov** [comment]
> A workaround would be to load everything before enabling fakefs (`Dir.glob` + `require` maybe) If the behavior changed between ruby versions then I think that means that the old ruby used some internal api and the new version uses `File.read` or some other fakefs method. It could help narrowing this down by making a simple example file (using bundler/inline) to reproduce this in 2 ruby versions ... I'd expect one of them to call some internal FakeFS method and the other to not do that.

Thanks for a quick reply and sorry it took me a while to get back. Thanks for the suggestions. Using `bundler/inline`, there is probably a way to see what methods are called internally, but I have been scratching my head about that.

**Comment by alishersadikov** [comment]
> I'm surprised you haven't run into this issue before. I've been having to clone since the dawn of time (Rails 4.x?).
> 
> I have no memory of how this code works - I wrote this 8+ years ago, but here it is in case it helps. This is from `spec_helper.rb`:
> 
> ```ruby
> # Support FakeFS helpers
> require 'fakefs/spec_helpers'
> require 'pp' # Resolves https://github.com/defunkt/fakefs/issues/215, https://github.com/defunkt/fakefs/issues/99
> 
> # Support for FakeFS::SpecHelpers::Rails
> module FakeFS
>   module SpecHelpers
>     module Rails
>       def self.extended(example_group)
>         example_group.use_fakefs_rails(example_group)
>       end
> 
>       def self.included(example_group)
>         example_group.extend FakeFS::SpecHelpers
>         example_group.extend self
>       end
> 
>       def use_fakefs_rails(describe_block)
>         describe_block.before :each do
>           unless FakeFS::FileSystem.unarchive(:rails)
>             FakeFS::FileSystem.clone(::Rails.root.join('app'))
>             FakeFS::FileSystem.clone(::Rails.root.join('config'))
>             FakeFS::FileSystem.clone(::Rails.root.join('public'))
>             FakeFS::FileSystem.clone(Gem.loaded_specs['jquery-rails'].full_gem_path)
>             FakeFS::FileSystem.clone(Gem.loaded_specs['coffee-script-source'].full_gem_path)
>             FileUtils.mkdir_p('/tmp')
>             FakeFS::FileSystem.archive(:rails)
>           end
>         end
>       end
>     end
>   end
> end
> ```
> 
> Then I just use `include FakeFS::SpecHelpers::Rails` in my rspec contexts.
> 
> The cool thing there is by using archive, I amortize the cost of cloning huge chunks of my Rails app across all the tests that need FakeFS.

This looks nice! We have a rudimentary, now inefficient way of doing this, by using a helper method: 

```
def within_stubbed_fs
    # some cruft here
    FakeFS.with_fresh do
       # now I have to clone the file system here 
       yield 
    end 
end 
```

I search for archive/unarchive methods and they don't seem to be in the source code. But I found the issue you had created @tovodeverett: https://github.com/fakefs/fakefs/issues/170, so maybe I can try to mimic that.
