### ISSUE TITLE
Can't use IRB when FakeFS is activated

### ISSUE THREAD

**Issue by mrzasa** [fakefs/fakefs#484]
IRB can't start when `FakeFS` is activated, because it can't open the history file. 

See the minimal example below:
```ruby
require 'fakefs'

RSpec.describe 'IRB inside FakeFS' do
  it 'works' do
    binding.irb
  end
end
```
it ends up with an error:
```ruby
    Failure/Error: Unable to find pry-fakefs/irb_spec.rb to read failed line
     
     Errno::ENOENT:
       No such file or directory - /home/mrzasa/.irb-history
     # ruby-3.0.4/gems/fakefs-1.8.0/lib/fakefs/file.rb:876:in `check_file_existence!'
     # ruby-3.0.4/gems/fakefs-1.8.0/lib/fakefs/file.rb:503:in `initialize'
     # ruby-3.0.4/gems/fakefs-1.8.0/lib/fakefs/kernel.rb:40:in `open'
     # ruby-3.0.4/gems/fakefs-1.8.0/lib/fakefs/kernel.rb:40:in `block in <module:Kernel>'
     # pry-fakefs/irb_spec.rb:5:in `block (2 levels) in <top (required)>'
```
This I believe is an effect of hijacking the `Kernel#open` method. To fix it we need to unhijack it in the IRB context.

Related to https://github.com/fakefs/fakefs/issues/290

Similar issue with pry is addressed in this PR: https://github.com/fakefs/fakefs/pull/485 (the pry problem is simpler though - it's enough to assign correctly mocked classes).

**Comment by grosser** [comment]
PR welcome
