### ISSUE TITLE
Isn't possible to flock

### ISSUE THREAD

**Issue by uvlad7** [fakefs/fakefs#501]
(This issue is just for tracking, PR is on it's way)
I believe it's safe to just return `true` from `File#flock`, as file lock is kept per process anyway, so it's not gonna lead to any false positives (not sure about `fork`, certainly wont work with `exec`, but this is something that won't work with fakefs anyway)
 
UPD: linux [man page](https://man7.org/linux/man-pages/man2/flock.2.html) says that if a process obtains multiple fd-s per one file, an attempt to flock more then one "may be denied", and it it's the case at least on 6.8.0 linux kernel, so it may break some code. And I'm not actually sure about "may be denied", `Pstore` seems to [rely](https://github.com/ruby/ruby/blob/v3_3_6/lib/pstore.rb#L617) on that, for example.
```bash
vladimir@np940x5n:~/fakefs (master)$ touch test_flock                                             
vladimir@np940x5n:~/fakefs (master)$ ln -s test_flock test_flock_link                                             
vladimir@np940x5n:~/fakefs (master)$ ln test_flock test_flock_hardlink                                               
vladimir@np940x5n:~/fakefs (master)$ irb                                                                                
3.0.2 :001 > f1 = File.open('test_flock', 'w')
 => #<File:test_flock> 
3.0.2 :002 > f1.flock File::LOCK_EX
 => 0 
3.0.2 :003 > f2 = File.open('test_flock_link')
 => #<File:test_flock_link> 
3.0.2 :004 > f2.flock File::LOCK_SH | File::LOCK_NB
 => false 
3.0.2 :005 > f3 = File.open('test_flock_hardlink')
 => #<File:test_flock_hardlink> 
3.0.2 :006 > f3.flock File::LOCK_SH | File::LOCK_NB
 => false 
3.0.2 :007 > f4 = File.open('test_flock')
 => #<File:test_flock> 
3.0.2 :008 > f4.flock File::LOCK_SH | File::LOCK_NB
 => false 
```

**Comment by uvlad7** [comment]
A reliable implementation is possible (on `FakeFS::FileSystem` level), but requires a proper synchronization, and for most tests simply return `true` is OK, I suppose, so I'm gonna just make it as an opt-in.

**Comment by grosser** [comment]
so you have a workaround now or you still want to make a PR ?

**Comment by uvlad7** [comment]
I'm still going to make a PR, just make this implementation not enabled by default and write a comment about when it's not safe to use

**Comment by grosser** [comment]
v2.6.0.
