### ISSUE TITLE
fakefs conflicts with pp on Ruby 1.9.3

### ISSUE THREAD

**Issue by mackuba** [fakefs/fakefs#99]
If pp is required after fakefs on Ruby 1.9.3, you get a superclass mismatch error, because pp monkey-patches File assuming that it extends IO, but since it's already the fake File, it extends StringIO:

```
$ ruby -v
ruby 1.9.3dev (2011-07-31 revision 32789) [x86_64-darwin10.8.0]
$ ruby -e "require 'fakefs'; require 'pp'"
/Users/psionides/.rvm/rubies/ruby-1.9.3-preview1/lib/ruby/1.9.1/pp.rb:399:in `<top (required)>': superclass mismatch for class File (TypeError)
    from /Users/psionides/.rvm/rubies/ruby-1.9.3-preview1/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/psionides/.rvm/rubies/ruby-1.9.3-preview1/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from -e:1:in `<main>'
```

Not sure what we can do about it though - maybe pp is the one to blame since it doesn't really have to specify superclass when monkey-patching an existing class?...

**Comment by bpinto** [comment]
What I did was to add a Gemfile to my gem and `require 'pp'`.

```
source "https://rubygems.org"

require 'pp' #https://github.com/defunkt/fakefs/issues/99
gemspec
```

**Comment by andrewdavidmackenzie** [comment]
FYI: I had to add the require to the Gemfile to get fakefs to work for me on ruby 2.1.5 and fakefs 0.8.0

**Comment by grosser** [comment]
this might fix the issue too:
```
gem 'fakefs', require: false
```

basically the problem is that Budler.require loads all gems listed in the gemspec ... so don't use it or change the gem to require false
